### ISSUE TITLE
currently breaking on installation of Rglpk and gurobi

### ISSUE THREAD

**Issue by njtierney** [njtierney/maxcovr#80]
It looks like the package is breaking on installation of Rglpk and gurobi for Travis:

![image](https://user-images.githubusercontent.com/6488485/58958487-59c7b980-87e6-11e9-9268-4db29e236343.png)

Which is stopping progress for #50.

It looks like `prioritizr` gets around the gurobi problem, they even have an [awesome vignette](https://cran.r-project.org/web/packages/prioritizr/vignettes/gurobi_installation.html) that explains how to install it

I'm not sure how to get around this problem - I'm going to tag @jeffreyhanson in to see if he might have some wise words of wisdom here

**Comment by jeffreyhanson** [comment]
Hi @njtierney! I hope everything's going well. Unfortunately, I don't really have any helpful solutions. At the moment, all of the tests in prioritizr which rely Gurobi are skipped on Travis (using `skip_if_not_installed("gurobi")`). Unfortunately, this means that we have to run tests locally in order to test if prioritizr is using Gurobi correctly, but I find the benefit of having access to Gurobi outweighs this cost. Perhaps one approach would be to try installing Gurobi on Travis and activating its 2-week demo mode automatically? It looks like you can download the Gurobi tarball from a static link on its website, but if you might need some clever coding in order to automatically find the filename for the latest version.

**Comment by njtierney** [comment]
Hey @jeffreyhanson !

So nice to hear from you! I'm good mate, hope things are going well in Porto, Portugal :)

Thanks for your advice! 

I would definitely run `skip_if_not_installed("gurobi")`, but I don't even use it in my tests. This was because I was worried I would trigger Travis errors. But I guess I can now use that.

But the confusing thing is that:

1. it seems to break on installing RGlpk - not sure how to stop that
2. gurobi is in Suggests (https://github.com/njtierney/maxcovr/blob/master/DESCRIPTION#L34)
3. travis does not install on suggests: https://github.com/njtierney/maxcovr/blob/master/.travis.yml#L13

I'm not quite sure how to solve this issue - the only thing I can think of right now is to clear the package cache on Travis. I'll see how that goes.

**Comment by njtierney** [comment]
OK so I went on a bit of a journey and found your thread, Jeff, on how travis builds on success: https://github.com/prioritizr/prioritizr/blob/master/.travis.yml

And then I have now shamelessly copied most of your travis YAML code here: https://github.com/prioritizr/prioritizr/blob/master/.travis.yml

Hopefully this helps solve the problem!

**Comment by mpadge** [comment]
Newly simplified way to express that stuff in travis; see [`osmdata` for demo](https://github.com/ropensci/osmdata) - all done via `addons`, rather than explicit `before_install` calls. `addons` are in this case ubuntu-explicit, and the other stuff you can put in the matrix for oxs. In case that helps ...

**Comment by njtierney** [comment]
Thanks, I it is solved now! 

![image](https://user-images.githubusercontent.com/6488485/59099696-324c2a80-8967-11e9-8f9d-695d3a32847a.png)


I had to include this line: https://github.com/njtierney/maxcovr/blob/master/.travis.yml#L38

Suggested by Rich FitzJohn and Bryce Mecum.

**Comment by jeffreyhanson** [comment]
Awesome! Glad to see you got it working. Just a heads up in case this causes issues for you later on, I sometimes find that R Ubuntu packages (e.g. `r-cran-rsymphony` and `r-cran-rglpk`) on Travis can sometimes fail to install when new versions of R get released, so I just manually install/`apt-get` the Ubuntu system packages manually (e.g. `coinor-libcgl-dev coinor-libclp-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libsymphony-dev coinor-libsymphony3` for SYMPHONY).
